FROM ubuntu:18.04

RUN apt-get update && apt-get install -y apt-transport-https && apt-get install -y cmake

RUN useradd -s /bin/bash -m vscode \
 && groupadd docker \
 && usermod -aG docker vscode

USER vscode
